# Plugin configuration for disableRedstone
# - disabled-blocks is a YAML list of block/material names to exclude from checks.
# Blocks for which interactions should be ignored (no special handling).
# - To turn a feature off, set the value to the boolean false

disabled-blocks:

features:
  redstone: true
  redstone-signals: true
  pistons: true
  dispensers: true
  hoppers: true
  tnt-priming: true
  explosions: true
  redstone-lamps: true
  fence_gates: true
  buttons: true
  trapdoors: true
  doors: true
