# Plugin configuration for disableRedstone
# - disabled-blocks is a YAML list of block/material names to exclude from checks.
# Blocks for which interactions should be ignored (no special handling).
# - To turn a feature off, set the value to the boolean false

disabled-blocks:

features:
  all-redstone: true
  redstone: true
  lever: true
  fence-gates: true
  buttons: true
  trapdoors: true
  doors: true
  pressure-plates: true
  tnt: true
  explosions: true
  pistons: true
  dispensers: true
  hoppers: true
  jukebox-disc: true
  redstone-lamp: true

