name: disableRedstone
version: 0.0.4
main: com.lokumotif.disableRedstone.DisableRedstone
api-version: '1.21'

commands:
  dr:
    description: Reload disableRedstone configuration
    usage: /dr reload
    permission: disableredstone.reload

permissions:
  disableredstone.reload:
    description: Allows reloading disableRedstone
    default: op
